name: CMake

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      # Some projects don't allow in-source building, so create a separate build directory
      # We'll use this as our working directory for all subsequent commands
      run: cmake -E make_directory ${{github.workspace}}/build
    - name: Installing Boost
      run: sudo apt-get install libboost-all-dev
      # Now we need to install mongodb
    - name: Installing gnupg
      run: sudo apt-get install gnupg
    - name: Importing mongodb keys
      run: wget -qO - https://www.mongodb.org/static/pgp/server-4.4.asc | sudo apt-key add -
    - name: Adding mongo repo to apt
      run: echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/4.4 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.4.list
    - name: updating apt tree
      run: sudo apt-get update
    - name: installing mongodb
      run: sudo apt-get install -y mongodb-org
    - name: starting mongodb
      run: sudo systemctl start mongod
    # installing libbson
    - name: Installing BSON
      run: sudo apt-get install libbson
    
    # installing mongocxx driver
    - name: downloading the mongocxx driver
      working-directory: ${{github.workspace}}
      run: curl -OL https://github.com/mongodb/mongo-cxx-driver/releases/download/r3.6.2/mongo-cxx-driver-r3.6.2.tar.gz
      
    - name: downloading the mongocxx driver
      working-directory: ${{github.workspace}}
      run: tar -xzf ${{github.workspace}}/mongo-cxx-driver-r3.6.2.tar.gz
      
    - name: configuring mongocxx
      working-directory: ${{github.workspace}}/mongo-cxx-driver-r3.6.2/build
      run: cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local
    - name: building and installing mongocxx
      working-directory: ${{github.workspace}}/mongo-cxx-driver-r3.6.2/build
      run: cmake --build . | sudo cmake --build . --target install
      
      
      
      
    - name: Configure CMake
      # Use a bash shell so we can use the same syntax for environment variable
      # access regardless of the host operating system
      shell: bash
      working-directory: ${{github.workspace}}/build
      # Note the current convention is to use the -S and -B options here to specify source 
      # and build directories, but this is only available with CMake 3.13 and higher.  
      # The CMake binaries on the Github Actions machines are (as of this writing) 3.12
      run: cmake $GITHUB_WORKSPACE -DBUILD_TESTS=ON

    - name: Test
      working-directory: ${{github.workspace}}/build
      shell: bash
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run: make -j 6
